name: Run Load Test with Secrets and Env
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Login (OIDC). If you use service principal JSON, replace with creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure Load Testing
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: loadtest/loadtest.config.yaml
          loadTestResource: ${{ vars.LOADTEST_RESOURCE_NAME }}
          resourceGroup: ${{ vars.LOADTEST_RESOURCE_GROUP }}

          # Pass a secret stored in GitHub
          secrets: |
            [
              { "name": "appToken", "value": "${{ secrets.MY_API_TOKEN }}" }
            ]

          # Pass a non-sensitive environment variable
          env: |
            [
              { "name": "webapp", "value": "myapp.contoso.com" }
            ]
