name: Run Azure Load Test
on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Azure login (OIDC). If using service principal JSON, replace this step per note below.
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run Load Test
        uses: azure/load-testing@v1
        with:
          loadTestConfigFile: loadtest/loadtest.config.yaml
          loadTestResource: ${{ vars.LOADTEST_RESOURCE_NAME }}
          resourceGroup: ${{ vars.LOADTEST_RESOURCE_GROUP }}
          loadTestRunName: run-${{ github.run_id }}
